# This file has been generated by node2nix 1.9.0. Do not edit!

#{pkgs ? import <nixpkgs> {
#    inherit system;
#  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs-12_x"}:
#
#let
#  nodeEnv = import ./node-env.nix {
#    inherit (pkgs) stdenv lib python2 runCommand writeTextFile writeShellScript;
#    inherit pkgs nodejs;
#    libtool = if pkgs.stdenv.isDarwin then pkgs.darwin.cctools else null;
#  };
#in
#import ./node-packages.nix {
#  inherit (pkgs) fetchurl nix-gitignore stdenv lib fetchgit;
#  inherit nodeEnv;
#}
# See https://nixos.wiki/wiki/Flakes#Using_flakes_project_from_a_legacy_Nix
(import
  (
    let
      lock = builtins.fromJSON (builtins.readFile ./flake.lock);
    in
    fetchTarball {
      url = "https://github.com/edolstra/flake-compat/archive/${lock.nodes.flake-compat.locked.rev}.tar.gz";
      sha256 = lock.nodes.flake-compat.locked.narHash;
    }
  )
  {
    src = ./.;
  }).defaultNix
